import { Agent, DashboardSummary, Run, World } from '@/lib/types';

export const mockDashboardSummary: DashboardSummary = {
  worlds: 4,
  activeAgents: 18,
  runningFlows: 7,
  failedRuns24h: 2,
};

export const mockWorlds: World[] = [
  {
    id: 'world-hospital-training',
    slug: 'hospital-training',
    name: 'Hospital Training World',
    description: 'Clinical rehearsal environment for triage, escalation, and bedside coordination.',
    status: 'active',
    region: 'HK-1',
    updatedAt: '2026-05-17T18:30:00Z',
    agentCount: 6,
    activeRunCount: 2,
    tags: ['clinical', 'simulation'],
  },
  {
    id: 'world-drone-inspection',
    slug: 'drone-inspection',
    name: 'Drone Inspection World',
    description: 'Facade and asset inspection workspace with perception agents and mission flows.',
    status: 'active',
    region: 'SG-1',
    updatedAt: '2026-05-17T17:20:00Z',
    agentCount: 5,
    activeRunCount: 3,
    tags: ['inspection', 'robotics'],
  },
  {
    id: 'world-neuromorphic-lab',
    slug: 'neuromorphic-lab',
    name: 'Neuromorphic Lab',
    description: 'Experimental environment for event-driven perception, memory traces, and adaptive policies.',
    status: 'paused',
    region: 'HK-2',
    updatedAt: '2026-05-16T09:45:00Z',
    agentCount: 4,
    activeRunCount: 1,
    tags: ['research', 'nepa'],
  },
  {
    id: 'world-sandbox-alpha',
    slug: 'sandbox-alpha',
    name: 'Sandbox Alpha',
    description: 'Fast iteration world for feature testing, event playback, and orchestration validation.',
    status: 'idle',
    region: 'LOCAL',
    updatedAt: '2026-05-17T15:10:00Z',
    agentCount: 3,
    activeRunCount: 1,
    tags: ['testing'],
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    worldId: 'world-hospital-training',
    name: 'Triage Coordinator',
    role: 'workflow-agent',
    status: 'online',
    model: 'gpt-4.1',
    lastSeenAt: '2026-05-17T18:28:00Z',
    throughputPerMin: 32,
  },
  {
    id: 'agent-2',
    worldId: 'world-hospital-training',
    name: 'Patient State Monitor',
    role: 'perception-agent',
    status: 'busy',
    model: 'vision-vlm',
    lastSeenAt: '2026-05-17T18:29:30Z',
    throughputPerMin: 18,
  },
  {
    id: 'agent-3',
    worldId: 'world-drone-inspection',
    name: 'Mission Planner',
    role: 'planner-agent',
    status: 'online',
    model: 'gpt-4.1-mini',
    lastSeenAt: '2026-05-17T17:19:00Z',
    throughputPerMin: 27,
  },
  {
    id: 'agent-4',
    worldId: 'world-drone-inspection',
    name: 'Facade Defect Detector',
    role: 'vision-agent',
    status: 'online',
    model: 'custom-cv-v2',
    lastSeenAt: '2026-05-17T17:18:10Z',
    throughputPerMin: 41,
  },
  {
    id: 'agent-5',
    worldId: 'world-neuromorphic-lab',
    name: 'Spike Memory Mapper',
    role: 'memory-agent',
    status: 'offline',
    model: 'snn-prototype',
    lastSeenAt: '2026-05-16T09:44:00Z',
    throughputPerMin: 0,
  },
];

export const mockRuns: Run[] = [
  {
    id: 'run-101',
    worldId: 'world-hospital-training',
    flowName: 'Sepsis escalation rehearsal',
    trigger: 'manual',
    status: 'running',
    startedAt: '2026-05-17T18:20:00Z',
    progress: 68,
    initiatedBy: 'Dickson',
    events: [
      {
        id: 'event-1',
        runId: 'run-101',
        timestamp: '2026-05-17T18:20:10Z',
        level: 'info',
        source: 'Scenario Loader',
        message: 'Clinical environment initialized with triage and bedside stations.',
      },
      {
        id: 'event-2',
        runId: 'run-101',
        timestamp: '2026-05-17T18:22:22Z',
        level: 'warning',
        source: 'Patient State Monitor',
        message: 'Oxygen saturation dropped below threshold; escalation branch activated.',
      },
      {
        id: 'event-3',
        runId: 'run-101',
        timestamp: '2026-05-17T18:25:41Z',
        level: 'success',
        source: 'Triage Coordinator',
        message: 'Escalation protocol acknowledged and handoff checklist completed.',
      },
    ],
  },
  {
    id: 'run-202',
    worldId: 'world-drone-inspection',
    flowName: 'Facade defect sweep',
    trigger: 'schedule',
    status: 'running',
    startedAt: '2026-05-17T17:00:00Z',
    progress: 44,
    initiatedBy: 'scheduler',
    events: [
      {
        id: 'event-4',
        runId: 'run-202',
        timestamp: '2026-05-17T17:00:20Z',
        level: 'info',
        source: 'Mission Planner',
        message: 'Waypoint set loaded for tower section B.',
      },
      {
        id: 'event-5',
        runId: 'run-202',
        timestamp: '2026-05-17T17:05:12Z',
        level: 'info',
        source: 'Facade Defect Detector',
        message: 'Detected 3 anomaly clusters requiring secondary review.',
      },
    ],
  },
  {
    id: 'run-303',
    worldId: 'world-neuromorphic-lab',
    flowName: 'Adaptive memory trace replay',
    trigger: 'api',
    status: 'failed',
    startedAt: '2026-05-16T09:10:00Z',
    finishedAt: '2026-05-16T09:18:00Z',
    progress: 100,
    initiatedBy: 'lab-api',
    events: [
      {
        id: 'event-6',
        runId: 'run-303',
        timestamp: '2026-05-16T09:10:05Z',
        level: 'info',
        source: 'Replay Engine',
        message: 'Temporal event sequence loaded from memory snapshot.',
      },
      {
        id: 'event-7',
        runId: 'run-303',
        timestamp: '2026-05-16T09:17:48Z',
        level: 'error',
        source: 'Spike Memory Mapper',
        message: 'Trace divergence exceeded tolerance window during replay.',
      },
    ],
  },
];
