import { supabase } from '@/lib/supabase';
import PDFDocument from 'pdfkit';

export type CompliancePackageOpts = {
  siteId: string;
  periodStart: Date;
  periodEnd: Date;
  requestedBy: { id: string; name: string; role: string };
};

export async function generateCompliancePackage(opts: CompliancePackageOpts): Promise<Buffer> {
  const [
    missions, checklists, defects,
    approvalReviews, sloMeasurements, sloCredits,
    privacyLogs, siteInfo,
  ] = await Promise.all([
    fetchMissions(opts),
    fetchChecklists(opts),
    fetchDefects(opts),
    fetchApprovalReviews(opts),
    fetchSLOMeasurements(opts),
    fetchSLOCredits(opts),
    fetchPrivacyLogs(opts),
    fetchSiteInfo(opts.siteId),
  ]);

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks: Buffer[] = [];
  doc.on('data', c => chunks.push(c));

  // Section 1 — Cover
  renderCover(doc, opts, siteInfo, missions.length);

  // Section 2 — Flight log
  doc.addPage();
  renderFlightLog(doc, missions);

  // Section 3 — Checklists
  doc.addPage();
  renderChecklists(doc, checklists);

  // Section 4 — AI defect analytics
  doc.addPage();
  renderDefectAnalytics(doc, defects);

  // Section 5 — Trajectory approval audit
  doc.addPage();
  renderApprovalAudit(doc, approvalReviews);

  // Section 6 — SLO compliance
  doc.addPage();
  renderSLOCompliance(doc, sloMeasurements, sloCredits);

  // Section 7 — Privacy compliance
  doc.addPage();
  renderPrivacyDeclaration(doc, privacyLogs, opts.requestedBy);

  doc.end();
  return new Promise((res, rej) => {
    doc.on('end', () => res(Buffer.concat(chunks)));
    doc.on('error', rej);
  });
}

// Section renderers (stubs)
function renderCover(doc: PDFKit.PDFDocument, opts: CompliancePackageOpts, site: any, missionCount: number) {
  doc
    .fontSize(22).font('Helvetica-Bold').text('ATLAS Inspection Compliance Report', { align: 'center' })
    .moveDown(0.5)
    .fontSize(12).font('Helvetica')
    .text(`Site: ${site?.name ?? opts.siteId}`, { align: 'center' })
    .text(`Period: ${fmt(opts.periodStart)} – ${fmt(opts.periodEnd)}`, { align: 'center' })
    .text(`Generated: ${fmt(new Date())}  ·  By: ${opts.requestedBy.name} (${opts.requestedBy.role})`, { align: 'center' })
    .moveDown(2)
    .fontSize(10)
    .text('This document is an audit package generated by AuraSense ATLAS for submission to:')
    .text('  · Civil Aviation Department — HKCAD SUA Order (Chapter 448G)')
    .text('  · Architectural Services Department (ArchSD) Building Inspection Division')
    .text('  · Buildings Department — External Wall Regular Inspection Programme')
    .moveDown(1)
    .text(`Total missions in period: ${missionCount}`)
    .text(`Policy version: atlas.approval.v1`)
    .text(`Package hash: [computed on finalize]`)
    .moveDown(2)
    .fontSize(8).fillColor('#666')
    .text('ATLAS is operated by AuraSense Limited, Hong Kong. ' +
      'All flight data is stored with cryptographic audit trails. ' +
      'Privacy protections comply with the Personal Data (Privacy) Ordinance (Cap. 486).');
}
function renderFlightLog(doc: PDFKit.PDFDocument, missions: any[]) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 2 — Flight Log').moveDown(0.5);
  doc.fontSize(8).font('Helvetica');
  const cols = ['Date', 'Mission ID', 'Drone Reg', 'Pilot', 'Duration', 'Area', 'Status'];
  const widths = [60, 90, 70, 80, 50, 80, 50];
  renderTableHeader(doc, cols, widths);
  for (const m of missions) {
    renderTableRow(doc, [
      fmt(new Date(m.promoted_at)),
      m.id?.slice(0,8),
      m.drone_registration ?? '—',
      m.approver_id ?? '—',
      m.duration_min ? `${m.duration_min}min` : '—',
      m.site_id,
      m.status,
    ], widths);
  }
}
function renderChecklists(doc: PDFKit.PDFDocument, checklists: any[]) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 3 — Pre/Post-Flight Checklists').moveDown(0.5);
  doc.fontSize(8).font('Helvetica');
  const cols = ['Type', 'Drone', 'Pilot', 'Signed By', 'Signed At', 'Items'];
  const widths = [40, 70, 70, 70, 80, 180];
  renderTableHeader(doc, cols, widths);
  for (const c of checklists) {
    renderTableRow(doc, [
      c.checklist_type,
      c.drone_registration,
      c.remote_pilot_id,
      c.signed_by,
      fmt(new Date(c.signed_at)),
      Array.isArray(c.items) ? c.items.map((i:any)=>`${i.item}:${i.passed?'✔':'✗'}`).join('; ') : '',
    ], widths);
  }
}
function renderDefectAnalytics(doc: PDFKit.PDFDocument, defects: any[]) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 4 — AI Defect Analytics').moveDown(0.5);
  const byType = groupBy(defects, 'defect_type');
  doc.fontSize(10).font('Helvetica').text(`Total defects identified: ${defects.length}`);
  doc.text(`Critical: ${defects.filter(d=>d.severity==='critical').length}  High: ${defects.filter(d=>d.severity==='high').length}  Medium: ${defects.filter(d=>d.severity==='medium').length}  Low: ${defects.filter(d=>d.severity==='low').length}`);
  doc.moveDown(0.5);
  doc.fontSize(8).font('Helvetica');
  const cols2 = ['Asset', 'Defect Type', 'Severity', 'Confidence', 'Status', 'Reviewed By'];
  const widths2 = [80, 80, 55, 60, 70, 90];
  renderTableHeader(doc, cols2, widths2);
  for (const d of defects.slice(0, 50)) { // cap at 50 rows, remainder in appendix
    renderTableRow(doc, [
      d.asset_id, d.defect_type,
      d.severity?.toUpperCase(), `${(d.confidence*100).toFixed(0)}%`,
      d.review_status ?? 'pending', d.reviewed_by ?? '—',
    ], widths2);
  }
  if (defects.length > 50) {
    doc.fontSize(8).text(`… and ${defects.length - 50} additional defects. See appendix.`);
  }
}
function renderApprovalAudit(doc: PDFKit.PDFDocument, reviews: any[]) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 5 — Trajectory Approval Audit').moveDown(0.5);
  doc.fontSize(9).font('Helvetica');
  for (const r of reviews) {
    doc
      .font('Helvetica-Bold').text(`Mission: ${r.mission_promotion_id?.slice(0,8) ?? '—'}`)
      .font('Helvetica')
      .text(`Decision: ${r.decision}  ·  Tier: ${r.approval?.tier}  ·  By: ${r.reviewer_email}  ·  At: ${fmt(new Date(r.decided_at))}`)
      .text(`Policy: ${r.approval?.policyVersion}`)
      .text(`Justification: ${r.justification}`)
      .text(`Reasons: ${r.approval?.reasons?.join('; ') ?? '—'}`)
      .moveDown(0.5);
  }
}
function renderSLOCompliance(doc: PDFKit.PDFDocument, measurements: any[], credits: any[]) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 6 — SLO Compliance').moveDown(0.5);
  const bySkill = groupBy(measurements, 'skill_id');
  for (const [skillId, rows] of Object.entries(bySkill) as any[]) {
    const slaMet = rows.filter((r: any) => r.sla_met).length;
    const pct = (slaMet / rows.length * 100).toFixed(1);
    doc.fontSize(10).font('Helvetica-Bold').text(`${skillId}  —  SLA compliance: ${pct}% (${slaMet}/${rows.length})`);
    doc.fontSize(8).font('Helvetica').text(`SLO compliance: ${(rows.filter((r:any)=>r.slo_met).length/rows.length*100).toFixed(1)}%`);
    const breachCredits = credits.filter((c: any) => c.skill_id === skillId);
    if (breachCredits.length) {
      doc.text(`Credits issued: ${breachCredits.length} breach(es), total HK$${breachCredits.reduce((s:number,c:any)=>s+c.credit_amount_hkd,0).toFixed(2)}`);
    }
    doc.moveDown(0.4);
  }
}
function renderPrivacyDeclaration(doc: PDFKit.PDFDocument, logs: any[], requestedBy: any) {
  doc.fontSize(14).font('Helvetica-Bold').text('Section 7 — Privacy Compliance Declaration').moveDown(0.5);
  const totalFrames = logs.reduce((s, l) => s + (l.identifiable_frames_detected ?? 0), 0);
  const retained = logs.reduce((s, l) => s + (l.identifiable_frames_retained ?? 0), 0);
  doc.fontSize(10).font('Helvetica')
    .text(`Total identifiable frames detected across all missions: ${totalFrames}`)
    .text(`Identifiable frames retained: ${retained}`)
    .text(`Auto-blur applied: ${logs.every(l=>l.blur_applied) ? 'YES — all missions' : 'PARTIAL — see log'}`)
    .moveDown(1)
    .text('Declaration:')
    .font('Helvetica-Bold')
    .text('All drone footage collected during this period has been processed in accordance with the Personal Data (Privacy) Ordinance (Cap. 486) and the guidance of the Housing Authority and the Office of the Privacy Commissioner for Personal Data. No identifiable images of residents have been retained. All auto-blur processes are irreversible.')
    .moveDown(1)
    .font('Helvetica')
    .text(`Declared by: ${requestedBy.name} (${requestedBy.role})`)
    .text(`Date: ${fmt(new Date())}`);
}

// Helpers
const fmt = (d: Date) => d.toISOString().slice(0,10);
const groupBy = (arr: any[], key: string) => arr.reduce((acc, item) => {
  (acc[item[key]] ??= []).push(item); return acc; }, {} as Record<string,any[]>);

function renderTableHeader(doc: PDFKit.PDFDocument, cols: string[], widths: number[]) {
  doc.font('Helvetica-Bold');
  let x = doc.page.margins.left;
  cols.forEach((c, i) => { doc.text(c, x, doc.y, { width: widths[i], lineBreak: false }); x += widths[i]; });
  doc.moveDown(0.3).moveTo(doc.page.margins.left, doc.y).lineTo(530, doc.y).stroke().font('Helvetica');
}

function renderTableRow(doc: PDFKit.PDFDocument, vals: string[], widths: number[]) {
  const y = doc.y;
  let x = doc.page.margins.left;
  vals.forEach((v, i) => { doc.text(v ?? '—', x, y, { width: widths[i], lineBreak: false }); x += widths[i]; });
  doc.moveDown(0.25);
}

// Data fetchers (stubs)
async function fetchMissions({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('mission_promotions')
    .select('*').eq('site_id', siteId)
    .gte('promoted_at', periodStart.toISOString())
    .lte('promoted_at', periodEnd.toISOString())
    .order('promoted_at');
  return data ?? [];
}
async function fetchChecklists({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('flight_checklists').select('*').eq('site_id', siteId)
    .gte('signed_at', periodStart.toISOString()).lte('signed_at', periodEnd.toISOString());
  return data ?? [];
}
async function fetchDefects({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('defect_annotations').select('*').eq('site_id', siteId)
    .gte('annotated_at', periodStart.toISOString()).lte('annotated_at', periodEnd.toISOString())
    .order('severity');
  return data ?? [];
}
async function fetchApprovalReviews({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('approval_reviews').select('*, mission_promotions!inner(site_id, promoted_at)')
    .eq('mission_promotions.site_id', siteId)
    .gte('decided_at', periodStart.toISOString()).lte('decided_at', periodEnd.toISOString());
  return data ?? [];
}
async function fetchSLOMeasurements({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('skill_slo_measurements').select('*').eq('site_id', siteId)
    .gte('measured_at', periodStart.toISOString()).lte('measured_at', periodEnd.toISOString());
  return data ?? [];
}
async function fetchSLOCredits({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('slo_credits').select('*').eq('site_id', siteId)
    .gte('issued_at', periodStart.toISOString()).lte('issued_at', periodEnd.toISOString());
  return data ?? [];
}
async function fetchPrivacyLogs({ siteId, periodStart, periodEnd }: CompliancePackageOpts) {
  const { data } = await supabase.from('privacy_compliance_log').select('*').eq('site_id', siteId)
    .gte('verified_at', periodStart.toISOString()).lte('verified_at', periodEnd.toISOString());
  return data ?? [];
}
async function fetchSiteInfo(siteId: string) {
  const { data } = await supabase.from('sites').select('name,address,operator').eq('id', siteId).single();
  return data;
}