// src/app/dashboard/agent-mode/page.tsx
"use client";

import { useEffect, useState } from "react";
import type { AtlasSkill } from "@/lib/skills/types";
import SkillCard from "@/components/skills/SkillCard";

export default function AgentModePage() {
  const [queue, setQueue] = useState<AtlasSkill[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchQueue = () => {
    fetch("/api/skills/approval-queue")
      .then((r) => r.json())
      .then((d) => setQueue(d.queue))
      .finally(() => setLoading(false));
  };

  useEffect(fetchQueue, []);

  const handleApprove = async (id: string) => {
    await fetch(`/api/skills/${id}/approve`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ approvedBy: "operator", action: "approve" }),
    });
    fetchQueue();
  };

  const handleReject = async (id: string) => {
    await fetch(`/api/skills/${id}/approve`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ approvedBy: "operator", action: "reject" }),
    });
    fetchQueue();
  };

  return (
    <div className="flex flex-col gap-6 p-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-white">
            NEPA Agent Mode
          </h1>
          <p className="text-sm text-zinc-400 mt-1">
            Skills self-generated by the neuromorphic agent pending human approval
          </p>
        </div>
        <span className="text-xs px-3 py-1.5 rounded-full bg-rose-900/40 text-rose-300 border border-rose-500/40 font-medium">
          🧠 Agent Active
        </span>
      </div>

      {/* Status banner */}
      <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-300">
        <strong>Autonomy Mode: SHADOW</strong> — Generated skills validated in
        sandbox but require operator approval before hardware deployment.
      </div>

      {/* Approval queue */}
      {loading ? (
        <div className="text-zinc-500 text-sm">Loading approval queue…</div>
      ) : queue.length === 0 ? (
        <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-8 text-center">
          <p className="text-zinc-500 text-sm">No skills pending approval</p>
          <p className="text-zinc-600 text-xs mt-1">
            NEPA will populate this queue during rehearsal when capabilities are
            missing
          </p>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-400">
            {queue.length} skill{queue.length > 1 ? "s" : ""} awaiting review
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            {queue.map((skill) => (
              <SkillCard
                key={skill.id}
                skill={skill}
                onApprove={handleApprove}
                onReject={handleReject}
              />
            ))}
          </div>
        </>
      )}

      {/* Pipeline explainer */}
      <div className="mt-4 rounded-xl border border-zinc-800 bg-zinc-900/50 p-5">
        <h2 className="text-sm font-semibold text-zinc-300 mb-3">
          Self-Extension Pipeline
        </h2>
        <ol className="flex flex-col gap-2 text-xs text-zinc-400">
          {[
            ["Capability Gap Detected", "NEPA detects a missing skill during rehearsal or live mission"],
            ["SkillIntent Drafted", "Agent emits structured intent: name, domain, I/O, safety level"],
            ["Schema Written", "AtlasSkill JSON Schema auto-generated from intent"],
            ["Code Stub Written", "TypeScript implementation stub generated, no external API calls"],
            ["Sandbox Validated", "Static AST gate + policy gate + property tests"],
            ["Approval Queue", "Operator reviews here — approve or reject"],
            ["Skill Registered", "On approval: promoted to active, visible in Skill Library"],
          ].map(([title, desc], i) => (
            <li key={i} className="flex gap-3">
              <span className="w-5 h-5 rounded-full bg-zinc-800 text-zinc-400 flex items-center justify-center flex-shrink-0 text-[10px] font-bold">
                {i + 1}
              </span>
              <span>
                <strong className="text-zinc-300">{title}</strong> — {desc}
              </span>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}